### ISSUE TITLE
v0.3.0 CSM login failed

### ISSUE THREAD

**Issue by faradawn** [Seagate/cortx-k8s#215]
### Problem

After deploying CORTX v0.3.0, tried to log in CMS (control service) with username `cortxadmin` and password `V1Acv%V8$2qL!JIP` with the following command:
```
curl -d '{"username": "cortxadmin", "password": "$control_password"}' https://$CSM_IP:8081/api/v2/login -k -i
```

But got a 401 unauthorized error:
```
I got an unauthorized error:
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Server: NULL
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self'; object-src 'self'
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
```

Used to be able to login to CSM on CORTX v.0.2.0 with the above commands. Wondered did I missed something? 

### Expected behavior

The CSM API should return a bearer token, instead of a 401 error.

### How to reproduce
1 - Deploy Kubernetes and CORTX
```
deploy kubernetes

git clone https://github.com/Seagate/cortx-k8s;

./prereq-deploy-cortx-cloud.sh -d /dev/sdb -s solution.example.yaml

kubectl taint node master node-role.kubernetes.io/master:NoSchedule-

./deploy-cortx-cloud.sh solution.example.yaml
```

2 - Try login CSM
```
control_password=$(kubectl get secrets/cortx-secret --namespace default --template={{.data.csm_mgmt_admin_secret}} | base64 -d) 

export CSM_IP=`kubectl get svc cortx-control-loadbal-svc -ojsonpath='{.spec.clusterIP}'`

curl -d '{"username": "cortxadmin", "password": "$control_password"}' https://$CSM_IP:8081/api/v2/login -k -i
```

### CORTX on Kubernetes version

v.0.3.0 on integration

### Deployment information

Kubernetes version: v1.23.5
kubectl version: latest
Cluster and Client OS: CentOS 7.8
Provider: Chameleon
Setup: four-node Kubernetes cluster, with master untainted (allowed scheduling). 

### Solution configuration file YAML

```yaml
# same as solution.example.yaml at integration branch
solution:
  namespace: default
  deployment_type: standard
  secrets:
    name: cortx-secret
    content:
      kafka_admin_secret: null
      consul_admin_secret: null
      common_admin_secret: null
      s3_auth_admin_secret: null
      csm_auth_admin_secret: null
      csm_mgmt_admin_secret: null
  images:
    cortxcontrol: ghcr.io/seagate/cortx-all:2.0.0-725
    cortxdata: ghcr.io/seagate/cortx-all:2.0.0-725
    cortxserver: ghcr.io/seagate/cortx-rgw:2.0.0-725
    cortxha: ghcr.io/seagate/cortx-all:2.0.0-725
    cortxclient: ghcr.io/seagate/cortx-all:2.0.0-725
    consul: ghcr.io/seagate/consul:1.11.4
    kafka: ghcr.io/seagate/kafka:3.0.0-debian-10-r7
    zookeeper: ghcr.io/seagate/zookeeper:3.8.0-debian-10-r9
    rancher: ghcr.io/seagate/local-path-provisioner:v0.0.20
    busybox: ghcr.io/seagate/busybox:latest
  common:
    storage_provisioner_path: /mnt/fs-local-volume
    container_path:
      local: /etc/cortx
      log: /etc/cortx/log
    s3:
      default_iam_users:
        auth_admin: "sgiamadmin"
        auth_user: "user_name"
        #auth_secret defined above in solution.secrets.content.s3_auth_admin_secret
      max_start_timeout: 240
      extra_configuration: ""
    motr:
      num_client_inst: 0
      start_port_num: 29000
      extra_configuration: ""
    hax:
      protocol: https
      service_name: cortx-hax-svc
      port_num: 22003
    storage_sets:
      name: storage-set-1
      durability:
        sns: 1+0+0
        dix: 1+0+0
    external_services:
      s3:
        type: NodePort
        count: 1
        ports:
          http: 80
          https: 443
        nodePorts:
          http: null
          https: null
      control:
        type: NodePort
        ports:
          https: 8081
        nodePorts:
          https: null
    resource_allocation:
      consul:
        server:
          storage: 10Gi
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 100m
        client:
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 100m
      zookeeper:
        storage_request_size: 8Gi
        data_log_dir_request_size: 8Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
      kafka:
        storage_request_size: 8Gi
        log_persistence_request_size: 8Gi
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 1
  storage:
    cvg1:
      name: cvg-01
      type: ios
      devices:
        metadata:
          device: /dev/sdc
          size: 5Gi
        data:
          d1:
            device: /dev/sdd
            size: 5Gi
          d2:
            device: /dev/sde
            size: 5Gi
  nodes:
    node1:
      name: master
    node2:
      name: node-1
    node3:
      name: node-2
    node4:
      name: node-3
```

### Logs

[deployment.log](https://github.com/Seagate/cortx-k8s/files/8522753/deployment.log)

### Additional information

na

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-30941. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by walterlopatka** [comment]
Hi @faradawn ,

If the instructions that you provided are literally what you typed, then I can see what might have gone wrong.

This curl statement attempts to expand the variable $control_password, but it is within single quotes, which prevents the variable expansion, so the password passed through curl would simply be "$control_password".
```
curl -d '{"username": "cortxadmin", "password": "$control_password"}' https://$CSM_IP:8081/api/v2/login -k -i
```

I tried with this line (my password is `2%jJKO$LyLv#R8rl`, similar to yours) and it fails:
```
[root@test-centos /]# control_password='2%jJKO$LyLv#R8rl'
[root@test-centos /]# CSM_IP=10.96.84.180
[root@test-centos /]# curl -d '{"username": "cortxadmin", "password": "$control_password"}' https://$CSM_IP:8081/api/v2/login -k -i
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Server: NULL
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self'; object-src 'self'
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Content-Length: 74
Date: Wed, 20 Apr 2022 19:18:29 GMT

{"error_code": 4113, "message": "Unauthorized", "message_id": "HttpError"}
```
and here it is passing with the literal password:
```
[root@test-centos /]# curl -d '{"username": "cortxadmin", "password": "2%jJKO$LyLv#R8rl"}' https://$CSM_IP:8081/api/v2/login -k -i
HTTP/1.1 200 OK
Authorization: Bearer 43a8b0c05a8a45acbb4d570c18948122
Content-Type: application/json
Content-Length: 25
Server: NULL
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Security-Policy: script-src 'self'; object-src 'self'
Referrer-Policy: no-referrer, strict-origin-when-cross-origin
Pragma: no-cache
Expires: 0
Cache-control: no-cache, no-store, must-revalidate, max-age=0
Date: Wed, 20 Apr 2022 19:19:03 GMT

{"reset_password": false}
```

(I also notice that not all pods are healthy/running, but I don't think this is related to your problem.)

Let me know if this is helpful.  If it is not, then I think I need more information.

If you still have a problem, one thing I would recommend is setting the password in the `solution.yaml` file, rather than letting the password be autogenerated.  It might be easier to diagnose the problem without special characters that the shell might interpret funny.

**Comment by walterlopatka** [comment]
I should add, when I suggest using a password without special characters, you need at least one.  For this kind of testing I use this setting in `solution.yaml`:
```
  secrets:
    name: cortx-secret
    content:
      csm_mgmt_admin_secret: Password@123
      s3_auth_admin_secret: Password@123
```
