### ISSUE TITLE
cortx-minikube-k8s-installation.md

### ISSUE THREAD

**Issue by johnbent** [Seagate/cortx-k8s#89]
@r-wambui , can you please work with @alfhad to make sure that the awesome google doc that @alfhad created becomes a fully working document and is contributed to our GitHub and linked appropriately from an existing page?
References:
[Slack Discussion](https://cortxcommunity.slack.com/archives/C0303CVU2TH/p1644220300127489)
[Google Doc](https://docs.google.com/document/d/1ahR5q1ZGEsouixlQ3C8lZUMX0BDotSswfZwo_el7WNs/edit)

Please reach out to @osowski if you have any questions about either how to get the document working or how to appropriately create documentation in this repo.

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/EOS-28539. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by alfhad** [comment]
Thanks! Rinku for helping with the doc.

**Comment by osowski** [comment]
I'll be working on getting an updated CONTRIBUTING.md in the root of https://github.com/Seagate/cortx-k8s this week. In the mean time, once there's something ready to PR for this issue, please open the PR targeting the `integration` branch and we'll get that reviewed and merged quickly.

Thanks! Feel free to tag me with any questions in this thread.

**Comment by madhavemuri** [comment]
@r-wambui : Use number of s3 instances as 1, it will reduce the resource requirement.

**Comment by alfhad** [comment]
@madhavemuri I tried reducing the number of s3 instances to 1 and I'm still facing the same problem.

solution.yaml :
```
    s3:
      num_inst: 1
      start_port_num: 28051
      max_start_timeout: 240
```

```
[root@car k8_cortx_cloud]# kubectl get pod
NAME                                READY   STATUS             RESTARTS      AGE
consul-client-jqf94                 1/1     Running            0             10m
consul-server-0                     1/1     Running            0             10m
cortx-control-5db85f4cf6-27cwx      4/4     Running            0             8m35s
cortx-data-car-75fbcc5947-w5blb     2/3     CrashLoopBackOff   4 (71s ago)   7m23s
cortx-ha-87b799bb8-l7f7j            3/3     Running            0             3m23s
cortx-server-car-7cc684cd8f-49wd2   5/5     Running            2 (81s ago)   5m33s
kafka-0                             1/1     Running            0             9m20s
openldap-0                          1/1     Running            0             10m
zookeeper-0                         1/1     Running            0             9m43s
```

**Comment by walterlopatka** [comment]
@alfhad , can you share the full solution.yaml so we can see all settings?  (In particular I would like to confirm that "setup_size" is set to "small".  (If it is set to large then it will aggressively use RAM, and this could cause a problem.)

**Comment by alfhad** [comment]
@walterlopatka This is my ```solution.yaml``` file. I see that the setup_size is set to large. Should I set it to small ?

```
[root@car k8_cortx_cloud]# cat solution.yaml 
solution:
  namespace: default
  secrets:
    name: cortx-secret
    content:
      openldap_admin_secret: seagate1
      kafka_admin_secret: Seagate@123
      consul_admin_secret: Seagate@123
      common_admin_secret: Seagate@123
      s3_auth_admin_secret: ldapadmin
      csm_auth_admin_secret: seagate2
      csm_mgmt_admin_secret: Cortxadmin@123
  images:
    cortxcontrolprov: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxcontrol: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxdataprov: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxdata: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxserver: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxha: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    cortxclient: ghcr.io/seagate/cortx-all:2.0.0-642-custom-ci
    openldap: ghcr.io/seagate/symas-openldap:2.4.58
    consul: ghcr.io/seagate/consul:1.10.0
    kafka: ghcr.io/seagate/kafka:3.0.0-debian-10-r7
    zookeeper: ghcr.io/seagate/zookeeper:3.7.0-debian-10-r182
    rancher: ghcr.io/seagate/local-path-provisioner:v0.0.20
    busybox: ghcr.io/seagate/busybox:latest
  common:
    setup_size: large
    storage_provisioner_path: /mnt/fs-local-volume
    container_path:
      local: /etc/cortx
      shared: /share
      log: /etc/cortx/log
    s3:
      num_inst: 1
      start_port_num: 28051
      max_start_timeout: 240
    motr:
      num_client_inst: 0
      start_port_num: 29000
    hax:
      protocol: https
      service_name: cortx-hax-svc
      port_num: 22003
    storage_sets:
      name: storage-set-1
      durability:
        sns: 1+0+0
        dix: 1+0+0
    external_services:
      type: LoadBalancer
    resource_allocation:
      consul:
        server:
          storage: 10Gi
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 100m
        client:
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 300Mi
              cpu: 100m
      openldap:
        resources:
          requests:
            memory: 1Gi
            cpu: 2
          limits:
            memory: 1Gi
            cpu: 2
      zookeeper:
        storage_request_size: 8Gi
        data_log_dir_request_size: 8Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
      kafka:
        storage_request_size: 8Gi
        log_persistence_request_size: 8Gi
        resources:
          requests:
            memory: 1Gi
            cpu: 250m
          limits:
            memory: 2Gi
            cpu: 1
  storage:
    cvg1:
      name: cvg-01
      type: ios
      devices:
        metadata:
          device: /dev/sdc
          size: 10Gi
        data:
          d1:
            device: /dev/sdd
            size: 10Gi
          d2:
            device: /dev/sde
            size: 10Gi
  nodes:
    node1:
      name: car
```
